### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by ryanblock**
### We really appreciate your commitment to improving Architect

To maintain a high standard of quality in our releases, before merging every pull request we ask that you've completed the following:

- [ ] Forked the repo and created your branch from `main`
- [ ] Made sure tests pass (run `npm it` from the repo root)
- [ ] Expanded test coverage related to your changes:
  - [ ] Added and/or updated unit tests (if appropriate)
  - [ ] Added and/or updated integration tests (if appropriate)
- [ ] Updated relevant documentation:
  - [ ] Internal to this repo (e.g. `readme.md`, help docs, inline docs & comments, etc.)
  - [ ] [Architect docs (arc.codes)](https://github.com/architect/arc.codes)
- [ ] Summarized your changes in `changelog.md`
- [ ] Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes

Please also be sure to completed the CLA (if you haven't already).

Learn more about [contributing to Architect here](https://arc.codes/intro/community).

Thanks again!

### CODE REVIEW

**Comment by lpsinger** [comment]
Binding ctrl-d to process termination will be confusing for users on Linux, UNIX, macOS --- pretty much any operating systems except for Windows. ctrl-c should terminate the sandbox on most operating systems except for Windows, and ctrl-d should terminate the sandbox on Windows.

Is it known why it is necessary to capture the key press directly, rather than relying on signal handling?

**Comment by ryanblock** [comment]
Not really sure where that feedback comes from. ctrl-D is used to quit Node and Ruby in macOS, for example, and is the keyboard shortcut used exclusively for quitting Deno and Python in macOS.

We are capturing keypresses to enable other other shortcuts. Signal handling hasn't worked for me but I'd be happy to look at a PR!

**Comment by lpsinger** [comment]
ctrl-D is used to quit REPLs (or any other program that expects input on stdin) on Linux, UNIX, and macOS because it is the end-of-file character. On Windows, it's ctrl-Z.

The architect CLI is not a REPL, so writing EOF to its stdin should not do anything.

**Comment by ryanblock** [comment]
Fair enough, Sandbox isn't a REPL. I'm still not sure where the harm is in using ctrl-D / EOF, but if there's a bug or issue that this resolves, let's resolve it. Is the concern that someone on *nix may accidentally type ctrl-D and quit when they did not mean to?

Separately, if you're advocating moving exit condition handling to `process.on($signals)` that's fine if you can get it working while retaining support for rehydration keypress events (https://github.com/architect/sandbox/blob/main/src/cli/_stdin.js#L13-L35).

**Comment by lpsinger** [comment]
I didn't realize that sandbox responded to those keypresses. Are they documented? Some documentation in the manual and some instructions printed to the command line would make them more discoverable.

There are probably two layers of bugs here:
1. It seems that Architect does not respond properly to SIGINT which is supposed to trigger graceful termination of the process. The special handling of the ctrl-C keypress probably worked around this bug without addressing the underlying cause.
2. The issue with intercepting ctrl-D is that it is an OS-specific localization and it is incorrect for some (most) operating systems. It would be equivalent to developing a GUI application that uses a Windows widget set on all operating systems rather than the native widget set. It's jarring.

**Pull request merged**
