### PR TITLE
Perform graceful termination on SIGINT or SIGTERM signals

### PR DESCRIPTION
**Pull request by lpsinger**
### We really appreciate your commitment to improving Architect

To maintain a high standard of quality in our releases, before merging every pull request we ask that you've completed the following:

- [ ] Forked the repo and created your branch from `main`
- [ ] Made sure tests pass (run `npm it` from the repo root)
- [ ] Expanded test coverage related to your changes:
  - [ ] Added and/or updated unit tests (if appropriate)
  - [ ] Added and/or updated integration tests (if appropriate)
- [ ] Updated relevant documentation:
  - [ ] Internal to this repo (e.g. `readme.md`, help docs, inline docs & comments, etc.)
  - [ ] [Architect docs (arc.codes)](https://github.com/architect/arc.codes)
- [ ] Summarized your changes in `changelog.md`
- [ ] Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes

Please also be sure to completed the CLA (if you haven't already).

Learn more about [contributing to Architect here](https://arc.codes/intro/community).

Thanks again!

### CODE REVIEW

**Comment by ryanblock** [comment]
@lpsinger did you still want to look at this?

**Comment by lpsinger** [comment]
Yes, this is still a serious problem for a project.

**Comment by ryanblock** [comment]
Ok! Just in case you missed it from https://github.com/architect/architect/issues/1479#issuecomment-1996081313:

> `process.on('exit', ...)`, `process.on('SIGINT', ...)`, `process.on('SIGTERM', ...)` are all assumed to be synchronous operations, whereas `sandbox.end()` is an asynchronous API (which is what I think folks would expect it to be). 

I've got a short window this morning, I'll take a quick look at an implementation in another PR.

**Comment by ryanblock** [comment]
→ https://github.com/architect/sandbox/pull/732

**Comment by ryanblock** [comment]
Best effort attempt at fixing this (within Arc's scope / capabilities) live in v11.0.8!

**Pull request closed without merging**
