### PR TITLE
feat: no hydrate

### PR DESCRIPTION
**Pull request by mawdesley**
### We really appreciate your commitment to improving Architect

To maintain a high standard of quality in our releases, before merging every pull request we ask that you've completed the following:

- [x] Forked the repo and created your branch from `master`
- [x] Made sure tests pass (run `npm it` from the repo root)
- [ ] Expanded test coverage related to your changes:
  - [ ] Added and/or updated unit tests (if appropriate)
  - [ ] Added and/or updated integration tests (if appropriate)
*no tests for hydration & can't see an obvious way to add them. Sorry!*
- [x] Updated relevant documentation:
  - [x] Internal to this repo (e.g. `readme.md`, help docs, inline docs & comments, etc.)
  - [x] [Architect docs (arc.codes)](https://github.com/architect/arc.codes)
  *happy to add if change is approved*
- [x] Summarized your changes in `changelog.md`
- [x] Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes

https://github.com/architect/architect/issues/1067

Please also be sure to completed the CLA (if you haven't already).

Learn more about [contributing to Architect here](https://arc.codes/intro/community).

Thanks again!

### CODE REVIEW

**Comment by ryanblock** [comment]
Will peep ASAP, this should probably also have a preferences setting too!

**Comment by mawdesley** [comment]
> this should probably also have a preferences setting too

:+1: added, not sure if this is the correct approach. Happy to change if you can point me towards another example?

Documentation PR here: https://github.com/architect/arc.codes/pull/327

**Comment by filmaj** [comment]
Hey y'all! I'm gonna look to merge this in shortly - thank you @mawdesley ! My only concern is the lack of testing. I'm going to rebase this PR with the latest master and take a stab at adding tests.

**Comment by ryanblock** [comment]
Hey, sorry this sat for so long. A few things have changed in Sandbox, but I'm still happy to merge if we can get it up to date. One thing to note is we now have this file for CLI flags: https://github.com/architect/sandbox/blob/master/src/lib/flags.js

Can we get this PR updated and fully tested? (Converting to draft until we do, thanks!)

**Comment by filmaj** [comment]
The use case for this PR for me was: we have a plugin that does bundling, so do not need arc to manage dependencies.

**Pull request closed without merging**
