### PR TITLE
⚙️ add travis ci

### PR DESCRIPTION
**Pull request by filmaj**

### CODE REVIEW

**Comment by ryanblock** [comment]
❤️🧡💛💚💙💜

**Comment by filmaj** [comment]
Looks like the build is stuck on one of the tests... will need to dig in later

**Comment by ryanblock** [comment]
I think this may be an AWS creds thing, try adding this to your travis config in the test line: `  - AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar REGION=us-west-1 npm run test`

**Comment by filmaj** [comment]
Hmm, if these tests are running against AWS, we should consider moving them to the architect/integration-tests repo I created and integrate them as a broader, more coarse-grained test suite on the architect/architect and architect/cli repos down the road a bit.

Though I don't think it's related to env vars. With no AWS related env vars, I can run the tests locally. It seems to get stuck somewhere inside `db.start` - comparing the test output on Travis to my local output, it doesn't look like the `db.start` callback ever gets invoked. It may be getting stuck somewhere in there.

**Comment by ryanblock** [comment]
The tests aren’t running against AWS, but when the local DB initializes, it creates a local endpoint to dynalite with the aws sdk, which itself requires credentials to complete initialization. If those creds aren’t present in an aws creds file or env vars, it has been known to hang.

**Comment by filmaj** [comment]
Ah yes that's it, I can repro locally if I remove my `~/.aws/*` files.

Adding the env vars to the travis build now and rerunning

**Comment by filmaj** [comment]
Yeppppp that was it

**Comment by filmaj** [comment]
Alright, this one's ready to merge now.

**Pull request merged**
