### PR TITLE
Fix getting the content-type of a response

### PR DESCRIPTION
**Pull request by herschel666**
Fixes the following error:

```
sandbox/src/http/invoke-http.js:71
              result.headers && result.headers['Content-Type'].startsWith(d) ||
                                                               ^

TypeError: Cannot read property 'startsWith' of undefined
    at documents.some.d (sandbox/src/http/invoke-http.js:71:64)
```

This is the most simple & stupid fix I can think of. If you'd like to have things tighten up a little codewise let me know.

### CODE REVIEW

**Comment by ryanblock** [comment]
Thanks! Out of curiosity, what are the repro steps to get that error? (Is it if a request is made without a content-type header?) I haven't seen this before.

**Comment by herschel666** [comment]
@ryanblock It's this code: https://github.com/herschel666/photoblog-upload/blob/a34988c99c7e649dbf1b89b834b4f859766355b8/server/src/http/get-favicon_ico/index.js#L7

So right now it just checks for the truthiness of the `.headers`-property and then immediately assumes that the `content-type`- and `Content-Type`-properties on it are of type `string`. Whereas at least one of the two properties seems to be `undefined` at the moment.

**Comment by ryanblock** [comment]
Ah, thanks! I see what's up. The headers will indeed always be strings, but they may not necessarily be present (or cased properly) if not run through Architect Functions, so we do need to defend against that with better nested node checks. Thanks!

**Comment by ryanblock** [comment]
Update: fix released in `1.2.11`

**Pull request merged**
