### PR TITLE
HTTP API support

### PR DESCRIPTION
**Pull request by ryanblock**

### CODE REVIEW

**Comment by filmaj** [comment]
Tried it out on an old REST project, if I use the `ARC_API_TYPE=rest` env var, works fine. If I don't, my application errors out expecting `queryStringParameters` to exist on the request object:

```
  let reset = req.queryStringParameters.reset;
```

If this is by design, we should call it out in our docs.

**Comment by ryanblock** [comment]
Yeah, definitely by design! The new default for Sandbox 2.0 is HTTP APIs with Lambda v2.0 payload shape (as that is the new default for Architect projects, and the reasoning behind bumping the Sandbox's major). This is going to need some documentation for sure.

Wondering what your thoughts were on the little warning when starting up in HTTP mode? Was it sufficient?

**Comment by filmaj** [comment]
Yeah definitely caught my eye to see the warning. Trying to dig through the diff in this PR but it's a lot, so going to ask instead: are we now detecting which API Gateway type is being used? Or is the warning shown every time?

**Comment by ryanblock** [comment]
Warning is shown every time (for now), I was thinking we'd get rid of it in a month or two. Didn't want Sandbox to phone back to AWS, though, because it's important that it functions completely offline / locally. Def open to other approaches though!

**Pull request merged**
