### PR TITLE
External Dynamo Database

### PR DESCRIPTION
**Pull request by m-butler**
After speaking with @ryanblock, he suggested I submit this PR to start the discussion on supporting external dynamo db providers/swapping out dynalite for something else.

### CODE REVIEW

**Comment by exalted** [comment]
FWIW I'd personally like to see this PR merged in sooner than later (ditching `dynalite` could be a separate, longer term, issue) since for the most part changes introduced in this PR seem to work with a local `dynamodb-local` instance.

My current workaround is to modify npm installed file manually, which is not ideal.

**Comment by ryanblock** [comment]
Been thinking about this; the reason I didn't merge yesterday for 6.5 is because I think this change belongs in the new rc format I'm working on (which I'm planning to be the marquee feature in 6.6): https://github.com/architect/architect/issues/763

If y'all are cool with me merging it as undocumented/not officially supported, and possibly phasing out the env var in the near future in favor of local config, I'll merge and release it today.

**Comment by exalted** [comment]
@ryanblock well, no biggie, as I am using my "editing the source code" workaround in the meantime for a super low-key side project. As long as you think you'll be releasing other stuff "soon", I don't really need this desperately. (I assume when new rc format will be merged, it won't necessarily mean this "feature" will be in it.)

I just wanted to highlight the fact that the PR works, and unless there were major pushbacks against it, we could've merged it even as is.

**Comment by ryanblock** [comment]
I'm hoping 6.6 will be released in July, but I'm not in a position to make any hard commitments right now, so I'll go ahead and release with the above caveats and we'll check back soon!

**Comment by ryanblock** [comment]
Released in `6.5.1`!

**Comment by exalted** [comment]
Yay! Thanks @ryanblock

**Pull request merged**
